source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target ‘helpMe’ do
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'SinchVerification-Swift'
    pod 'InputMask'
end
